name: Generate Release

on:
  push:
    tags:        
      - '*'

env:
  RELEASE_VERSION: ${{ github.ref }}

jobs:
  GenerateRelease:
    name: Generate Release Preview Distribution
    runs-on: windows-latest
    if: contains(github.ref, 'release')
    strategy:
      matrix:
        python-version: [ "3.11" ]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install App Dependencies
        run: |
          python -m pip install --upgrade pip
          if (Test-Path "src\Application\requirements.txt") { pip install -r src\Application\requirements.txt }

      - name: Generate dist folder
        run: python src\Application\build_windows_script.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-game-artifact
          path: src\Application\dist
  
  CreateReleasePreview:
    name: Create Release Preview
    runs-on: ubuntu-latest
    needs: GenerateRelease
    
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: compiled-game-artifact
          path: dist/

      - name: Generate Tag Number
        run: echo VERSION=$(sed -E 's/.*\/([0-9]+\.[0-9]+\.[0-9]+)$/\1/' <<< $RELEASE_VERSION) >> $GITHUB_ENV

      - name: run
        run: ls
  
      - name: run dist
        run: ls dist

      - name: Install zip
        uses: montudor/action-zip@v1
      
      - name: Zip output
        run: zip -qq -r chess.zip dist
        working-directory: .
      
      - name: run
        run: ls

      - name: Create release preview
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.zip 
          tag_name: ${{ env.VERSION }}         
          name: Release Preview - ${{ env.VERSION }}
          body: This is a preview of the release ${{ env.VERSION }}.
          prerelease: true