name: Python package

on: [push]

jobs:




  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
        python-version: ${{ matrix.python-version }}

      - name: Install Application Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f src/Chess.Application/requirements.txt ]; then pip install -r src/Chess.Application/requirements.txt; fi

      - name: Install Test Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f src/Chess.Tests/requirements.txt ]; then pip install -r src/Chess.Tests/requirements.txt; fi
            
  Linting:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -name: Linting
      run: |
        # stop the build if there are Python syntax errors or undefined names
        ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
        # default set of ruff rules with GitHub Annotations
        ruff --format=github --target-version=py37 .

  UnitTests:
    runs-on: ubuntu-latest
    needs: Linting
    steps:
      - name: Test with pytest
        run: |
          pytest --cov=./ --cov-report=xml --doctest-modules

  SonarCloudScan:
    runs-on: ubuntu-latest
    needs: UnitTests
    steps:
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

#  build2:
#
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        python-version: ["3.11"]
#
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#      - name: Set up Python ${{ matrix.python-version }}
#        uses: actions/setup-python@v4
#        with:
#          python-version: ${{ matrix.python-version }}
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install ruff pytest
#          if [ -f src/Chess.Tests/requirements.txt ]; then pip install -r src/Chess.Tests/requirements.txt; fi
#      - name: Lint with ruff
#        run: |
#          # stop the build if there are Python syntax errors or undefined names
#          ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
#          # default set of ruff rules with GitHub Annotations
#          ruff --format=github --target-version=py37 .
#      - name: Test with pytest
#        run: |
#          pytest --cov=./ --cov-report=xml --doctest-modules
#      - name: SonarCloud Scan
#        uses: SonarSource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}